### ISSUE TITLE
Memory leak providing RPC configs

### ISSUE THREAD

**Issue by hdmiimdh** [okp4/okp4d#208] opened 2022-11-14 08:49 UTC
We're providing RPC with other services for OKP4 testnet (okp4-nemeton) What I've noticed recently is extremely high consumption of our DS resources (16CPU/64GB RAM/32GB SWAP), literally ALL possible resources are gone less then in few hours. We had to shut down our RPC until it's fixed. 

We don't see the same issue with pruning custom 100/0/10. Only the following configs cause it:

Pruning: custom/100/2000/10 
Snapshot-interval: 2000

<img width="1259" alt="Screen Shot 2022-11-14 at 11 49 05" src="https://user-images.githubusercontent.com/27004732/201615834-05f657db-e918-416a-bcce-9aa84a671e93.png">

**Comment by amimart** [comment] 2022-11-14 10:06
@hdmiimdh Thanks for reporting that, we'll take a look a it!

**Comment by ccamel** [comment] 2023-03-21 13:32
@amimart any progress? Still relevant?

**Comment by amimart** [comment] 2023-03-21 13:38
@ccamel I couldn't reproduce the behavior, besides the codebase has changed a lot since this issue was reported. I'm in favor to close this one, the nemeton testnet phase 4 being oriented on resources consumption we may have more context if still relevant.

**Closed** 2023-03-21 13:56 UTC
